### ISSUE TITLE
dns.exception.SyntaxError: Text input is malformed.

### ISSUE THREAD

**Issue by moein9** [hannob/snallygaster#53]
hello, men thanks for these amazing tools,
I got this error when I try to run it on my VPS

Oh oh... an unhandled exception has happened. This shouldn't be.
Please report a bug and include all output.

called with
/usr/local/bin/snallygaster example.com -d

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dns/inet.py", line 87, in af_for_address
    dns.ipv4.inet_aton(text)
  File "/usr/local/lib/python3.8/dist-packages/dns/ipv4.py", line 52, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dns/inet.py", line 91, in af_for_address
    dns.ipv6.inet_aton(text, True)
  File "/usr/local/lib/python3.8/dist-packages/dns/ipv6.py", line 165, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/snallygaster", line 936, in <module>
    test(host)
  File "/usr/local/bin/snallygaster", line 728, in test_axfr
    axfr = dns.zone.from_xfr(dns.query.xfr(r, qhost))
  File "/usr/local/lib/python3.8/dist-packages/dns/zone.py", line 1184, in from_xfr
    for r in xfr:
  File "/usr/local/lib/python3.8/dist-packages/dns/query.py", line 919, in xfr
    (af, destination, source) = _destination_and_source(where, port,
  File "/usr/local/lib/python3.8/dist-packages/dns/query.py", line 226, in _destination_and_source
    af = dns.inet.af_for_address(where)
  File "/usr/local/lib/python3.8/dist-packages/dns/inet.py", line 94, in af_for_address
    raise ValueError
ValueError

**Comment by hannob** [comment]
This looks like an issue within dnspython parsing AXFR answers, though am I assuming rightly that you didn't get this error on example.com, but on a domain of your own you don't want to share here?

This is likely some unusual (buggy?) answer of the DNS server. Which version of dnspython are you using and can you share any information about the DNS server?

**Comment by moein9** [comment]
thanks for your reply the issue is not a target I think it is related to some python files I solved the problem just by trying to uninstall and installing some related things like python and dnspython and snallygaster actually I don't know what was exactly cause the problem.
