### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by KommX** [hannob/snallygaster#56]
When running `./snallygaster -d hkk.de` snallygaster crashes with the following output:

```
[[debug]] All hosts: hkk.de,www.hkk.de
[[debug]] Scanning hkk.de
[[debug]] Running test_lfm_php test
[[debug]] Running test_idea test
[[debug]] Running test_symfony_databases_yml test
[[debug]] Running test_rails_database_yml test
[[debug]] Running test_git_dir test
[[debug]] Running test_svn_dir test
[[debug]] Running test_apache_server_status test
[[debug]] Running test_coredump test
[[debug]] Running test_sftp_config test
[[debug]] Running test_wsftp_ini test
[[debug]] Running test_filezilla_xml test
[[debug]] Running test_winscp_ini test
[[debug]] Running test_ds_store test
[[debug]] Running test_php_cs_cache test
[[debug]] Running test_backupfiles test
[[debug]] Checking 404 page state of http://hkk.de/stutpqto.htm
[[debug]] Checking 404 page state of https://hkk.de/eyahirwt.htm
[[debug]] Running test_backup_archive test
[[debug]] Running test_deadjoe test
[[debug]] Running test_sql_dump test
[[debug]] Running test_bitcoin_wallet test
[[debug]] Running test_drupal_backup_migrate test
[[debug]] Running test_magento_config test
[[debug]] Running test_xaa test
[[debug]] Running test_optionsbleed test
[[debug]] Running test_privatekey test
[[debug]] Running test_sshkey test
[[debug]] Running test_dotenv test
[[debug]] Running test_invalidsrc test
[[debug]] Running test_ilias_defaultpw test
[[debug]] Running test_cgiecho test
[[debug]] Running test_phpunit_eval test
[[debug]] Running test_acmereflect test
[[debug]] Running test_drupaldb test
[[debug]] Running test_phpwarnings test
[[debug]] Running test_adminer test
[[debug]] Running test_elmah test
[[debug]] Running test_citrix_rce test
[[debug]] Running test_installer test
[[debug]] Running test_wpsubdir test
[[debug]] Running test_axfr test
/home/osboxes/snallygaster/./snallygaster:706: DeprecationWarning: please use dns.resolver.resolve() instead
  ns = dns.resolver.query(qhost, 'NS')
Oh oh... an unhandled exception has happened. This shouldn't be.
Please report a bug and include all output.

called with
./snallygaster -d hkk.de

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dns/inet.py", line 87, in af_for_address
    dns.ipv4.inet_aton(text)
  File "/usr/lib/python3.9/site-packages/dns/ipv4.py", line 52, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dns/inet.py", line 91, in af_for_address
    dns.ipv6.inet_aton(text, True)
  File "/usr/lib/python3.9/site-packages/dns/ipv6.py", line 165, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/osboxes/snallygaster/./snallygaster", line 916, in <module>
    test(host)
  File "/home/osboxes/snallygaster/./snallygaster", line 712, in test_axfr
    axfr = dns.zone.from_xfr(dns.query.xfr(r, qhost))
  File "/usr/lib/python3.9/site-packages/dns/zone.py", line 1184, in from_xfr
    for r in xfr:
  File "/usr/lib/python3.9/site-packages/dns/query.py", line 919, in xfr
    (af, destination, source) = _destination_and_source(where, port,
  File "/usr/lib/python3.9/site-packages/dns/query.py", line 226, in _destination_and_source
    af = dns.inet.af_for_address(where)
  File "/usr/lib/python3.9/site-packages/dns/inet.py", line 94, in af_for_address
    raise ValueError
ValueError
```

OS: Fedora 33
kernel: 5.8.18-300.fc33.x86_64

**Comment by hannob** [comment]
Which version is this? This looks like neither the latest git code nor the latest release.

I can't reproduce it, can you try if the same happens with the latest git code?

**Comment by KommX** [comment]
Ah, ok. I didn't notice that the default branch now was switched to _main_. I was still stuck on _master_. So the bug report is valid for _master_, but not for _main_.
It's up to you to decide if this is a valid bug report then. I'm fine with using _main_.

**Comment by hannob** [comment]
Ok that code has been rewritten and no longer works like this. If you see it with the current main branch or the latest release please open another bug.
